version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: outpilot-db
    environment:
      POSTGRES_USER: outpilot
      POSTGRES_PASSWORD: outpilot
      POSTGRES_DB: outpilot
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
