packages:
  - admin/backend
  - admin/frontend
  - portfolio
ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - prisma
  - unrs-resolver
